In [2]:
from selenium import webdriver
from bs4 import BeautifulSoup
import requests as requests
import pandas as pd
import numpy as np

In [7]:
URL = 'https://old.nasdaq.com/markets/ipos/activity.aspx?tab=pricings&month=2020-03'
page = requests.get(URL)
soup = BeautifulSoup(page.content, 'html.parser')
table = soup.find('table')
tablerows = table.find_all('tr')
combined = []
for tr in tablerows:
    td = tr.find_all('td')
    if not td:
        continue
    row = [i.text for i in td]
    combined.append(row)
data = np.array(combined)

dataset = pd.DataFrame({'Company Name': data[:,0], 'TIC' : data[:,1], 'Exchange' : data[:,2],
                       'Price': data[:,3], 'Shares': data[:,4], 'Offer Amount': data[:,5], 'Date': data[:,6] })
dataset

,Company Name,TIC,Exchange,Price,Shares,Offer Amount,Date
0,IMARA INC.,IMRA,NASDAQ Global Select,$16,"4,700,000","$75,200,000",3/12/2020
1,DFP HEALTHCARE ACQUISITIONS CORP.,DFPHU,NASDAQ Capital,$10,"20,000,000","$200,000,000",3/11/2020
2,FLYING EAGLE ACQUISITION CORP.,FEACU,NYSE,$10,"60,000,000","$600,000,000",3/6/2020
3,LIFESCI ACQUISITION CORP.,LSACU,NASDAQ Capital,$10,"6,000,000","$60,000,000",3/6/2020
4,GFL ENVIRONMENTAL INC.,GFL,NYSE,$19,"75,000,000","$1,425,000,000",3/3/2020

In [3]:
from datetime import datetime
baseURL = 'https://old.nasdaq.com/markets/ipos/activity.aspx?tab=pricings&month='
dates = pd.date_range('1980-01', '2020-03', freq = "M")
str_dates = []
for index in range(len(dates)):
    temp=str(dates[index])
    str_dates.append(temp)
    str_dates[index] = str_dates[index][0:7]

In [4]:
URLS = []
for val in str_dates:
    tempURL = baseURL + val
    URLS.append(tempURL)

In [5]:
month = []
for val in URLS:
    page = requests.get(val)
    soup = BeautifulSoup(page.content, 'html.parser')
    orange = soup.find(class_ = "orange-box")
    if orange !=None:
        continue
    table = soup.find('table')
    tablerows = table.find_all('tr')
    for tr in tablerows:
        td = tr.find_all('td')
        if not td:
            continue
        row = [i.text for i in td]
        month.append(row)
total = np.array(month)

totaldataset = pd.DataFrame({'Company Name': total[:,0], 'TIC' : total[:,1], 'Exchange' : total[:,2],
                      'Price': total[:,3], 'Shares': total[:,4], 'Offer Amount': total[:,5], 'Date': total[:,6] })

In [6]:
totaldataset

,Company Name,TIC,Exchange,Price,Shares,Offer Amount,Date
0,CERUS CORP,CERS,NASDAQ,$12,"2,000,000","$24,000,000",1/31/1997
1,ERGOBILT INC,ERGB,NASDAQ,$7,"1,700,000","$11,900,000",1/31/1997
2,APPIANT TECHNOLOGIES INC,NHAN,NASDAQ,$4,"2,300,000","$9,200,000",1/31/1997
3,TRIGON HEALTHCARE INC,TGH,New York Stock Exchange,$13,"15,500,000","$201,500,000",1/31/1997
4,MEDICAL MANAGER CORP,MMGR,NASDAQ,$11,"6,000,000","$66,000,000",1/30/1997
...,...,...,...,...,...,...,...
5687,"PPD, INC.",PPD,NASDAQ Global Select,$27,"60,000,000","$1,620,000,000",2/6/2020
5688,"SCHRODINGER, INC.",SDGR,NASDAQ Global Select,$17,"11,882,352","$201,999,984",2/6/2020
5689,BEAM THERAPEUTICS INC.,BEAM,NASDAQ Global Select,$17,"10,588,236","$180,000,012",2/6/2020
5690,CASPER SLEEP INC.,CSPR,NYSE,$12,"8,350,000","$100,200,000",2/6/2020
5691,INTERPRIVATE ACQUISITION CORP.,IPV'U,NYSE,$10,"21,000,000","$210,000,000",2/4/2020

In [22]:
page = requests.get("https://old.nasdaq.com/markets/ipos/activity.aspx?tab=pricings&month=2016-01")
soup = BeautifulSoup(page.content, 'html.parser')
orange = soup.find(class_ = "orange-box")
print(orange)

<div class="orange-box">There is no data for this month, please select a prior month.</div>

In [36]:
totaldataset.to_csv('Nasdaq_IPODates.csv')